"""Q8: regime comparator — does the cross-sectional law hold across time?

Phase 4 tests whether the Q4/Q6 cross-sectional findings from a single
month (June 2023, the "baseline") survive in other market regimes. This
module never touches raw data or `data/` — it is a pure downstream
comparator that loads already-computed `q4_cross_section.json` (required)
and `q6_endogeneity.json` (optional — a regime dir may not have a Q6 run
yet, or Q6 may not have been run for that period at all) from a baseline
directory and one or more regime directories, then:

1. **Recomputes** every cross-sectional regression (γ̂ vs log10(activity),
   p_flip vs log10(activity), and α̂_median vs log10(activity) when Q6 is
   present) from the per-symbol records using this module's own numpy OLS
   — the upstream json's stored `regressions` / `activity_regression`
   blocks are never trusted blindly. The recomputed numbers are
   cross-checked against the stored ones and any material mismatch is
   reported as an explicit warning in the output json rather than silently
   overwritten or ignored (a mismatch would mean either this module's OLS
   disagrees with q4/q6's OLS, or the upstream json was hand-edited /
   generated by a different code version — both are worth surfacing).
2. **Cross-regime comparison**: symbol-overlap sets (baseline ∩ each
   regime), survivorship (baseline symbols absent from a regime, split
   into "skipped below min_events" vs "failed/missing" using that
   regime's own q4 `skips`/`failures` lists when available), Spearman
   rank correlation of p_flip / γ / α across each regime pair on the
   overlap (implemented via numpy average-rank ranking — no scipy), and a
   law-stability table: same-sign check on the flip-law slope across all
   regimes, slope ratio vs. baseline, and a γ-invariance verdict (flat in
   every regime iff every regime's γ-vs-activity R² < 0.05).
3. **Outputs**: `q8_regimes.{md,json,png}` — the png has three panels
   (flip-law overlay across regimes, γ-vs-activity overlay across
   regimes, and a symbol-level p_flip baseline-vs-regime scatter with a
   y=x reference line for the first non-baseline regime, if any).

All law-stability verdicts in the md are phrased FROM the recomputed
numbers (f-strings driven by sign/ratio/R² comparisons) — the template
text does not hardcode which conclusion ("law holds" vs "law breaks
down") is correct; either outcome is a valid finding and must read
correctly regardless of what the data says.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# Regression-mismatch tolerance: recomputed vs. stored slope/intercept/r2
# are flagged as a warning if they differ by more than this absolute
# amount. This is deliberately loose (both sides use the same
# `np.polyfit(..., deg=1)` machinery on the same records, so an exact
# match is expected in the ordinary case) — it exists to catch a real
# discrepancy (different symbol set, stale json, code drift) without
# flagging float-noise-level differences.
REGRESSION_MISMATCH_TOL = 1e-6

# γ-invariance verdict threshold: a regime's γ-vs-activity regression is
# considered "flat" (no detectable activity dependence) when its R² falls
# below this. Matches the informal "R² < 0.05" bar already used in Q4's
# own findings language for a weak/no relationship.
GAMMA_FLAT_R2_THRESHOLD = 0.05


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def _load_regime(regime_dir: Path) -> dict:
    """Load a regime's q4 (required) and q6 (optional) json.

    Returns {"q4": <dict>, "q6": <dict | None>}. Raises FileNotFoundError
    with a clear message if q4_cross_section.json is absent — a regime
    dir with no Q4 run is not a valid input to this comparator at all,
    unlike Q6 which is genuinely optional per the plan.
    """
    q4_path = regime_dir / "q4_cross_section.json"
    if not q4_path.exists():
        raise FileNotFoundError(f"required q4_cross_section.json not found in {regime_dir}")
    q6_path = regime_dir / "q6_endogeneity.json"
    q6 = _load_json(q6_path) if q6_path.exists() else None
    return {"q4": _load_json(q4_path), "q6": q6}


# ---------------------------------------------------------------------------
# OLS (own implementation — never trust the upstream jsons' regression blocks)
# ---------------------------------------------------------------------------


def _ols_with_intercept(x: np.ndarray, y: np.ndarray) -> dict | None:
    """OLS slope/intercept/stderr/R²/n via np.polyfit, with intercept.

    Mirrors q4_cross_section._ols_with_intercept / q6_endogeneity's
    identical helper exactly (same machinery, deliberately reimplemented
    here rather than imported, since this module's job is to independently
    recompute and cross-check — importing the upstream helper would defeat
    that purpose if the upstream implementation itself had drifted).
    Returns None if fewer than 3 points or x has zero variance.
    """
    if x.size < 3 or np.ptp(x) == 0.0:
        return None
    (slope, intercept), cov = np.polyfit(x, y, 1, cov=True)
    yhat = slope * x + intercept
    resid = y - yhat
    ss_res = float(resid @ resid)
    ss_tot = float(((y - y.mean()) ** 2).sum())
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else 0.0
    return {
        "slope": float(slope),
        "intercept": float(intercept),
        "stderr": float(np.sqrt(cov[0, 0])),
        "r2": r2,
        "n": int(x.size),
    }


def _recompute_q4_regressions(q4_records: list[dict]) -> dict:
    """Recompute gamma_vs_activity and p_flip_vs_activity from raw records."""
    if not q4_records:
        return {"gamma_vs_activity": None, "p_flip_vs_activity": None}
    log_n = np.array([np.log10(r["n_events"]) for r in q4_records])
    gamma = np.array([r["gamma"] for r in q4_records])
    p_flip = np.array([r["p_flip"] for r in q4_records])
    return {
        "gamma_vs_activity": _ols_with_intercept(log_n, gamma),
        "p_flip_vs_activity": _ols_with_intercept(log_n, p_flip),
    }


def _recompute_q6_regression(q6_records: list[dict]) -> dict | None:
    if not q6_records:
        return None
    log_n = np.array([np.log10(r["n_events"]) for r in q6_records])
    alpha_med = np.array([r["alpha_median"] for r in q6_records])
    return _ols_with_intercept(log_n, alpha_med)


def _reg_mismatch(recomputed: dict | None, stored: dict | None) -> str | None:
    """Compare a recomputed regression dict to the stored one; return a warning string or None.

    Both None -> no mismatch (both agree nothing was estimable). One None
    and the other not -> mismatch (estimability itself disagrees). Both
    present -> compare slope/intercept/r2 within REGRESSION_MISMATCH_TOL.
    """
    if recomputed is None and stored is None:
        return None
    if recomputed is None or stored is None:
        return (
            f"estimability mismatch: recomputed={'present' if recomputed else 'None'}, "
            f"stored={'present' if stored else 'None'}"
        )
    diffs = {
        k: abs(recomputed[k] - stored[k])
        for k in ("slope", "intercept", "r2")
        if k in stored
    }
    bad = {k: v for k, v in diffs.items() if v > REGRESSION_MISMATCH_TOL}
    if not bad:
        return None
    parts = ", ".join(f"{k} differs by {v:.6g}" for k, v in bad.items())
    return f"recomputed regression disagrees with stored json: {parts}"


# ---------------------------------------------------------------------------
# Spearman rank correlation (own implementation, no scipy)
# ---------------------------------------------------------------------------


def _average_ranks(values: np.ndarray) -> np.ndarray:
    """Rank `values` ascending, tied values getting the average of their ranks (1-indexed).

    E.g. [10, 20, 20, 30] -> ranks [1.0, 2.5, 2.5, 4.0]. This is the
    standard tie-handling convention Spearman's rho uses (equivalent to
    scipy.stats.rankdata(method="average")), reimplemented here since this
    module deliberately avoids a scipy dependency.
    """
    order = np.argsort(values, kind="mergesort")
    sorted_vals = values[order]
    n = values.size
    ranks = np.empty(n, dtype=np.float64)

    i = 0
    while i < n:
        j = i
        while j + 1 < n and sorted_vals[j + 1] == sorted_vals[i]:
            j += 1
        # Positions i..j (0-indexed) are tied; average 1-indexed rank.
        avg_rank = (i + 1 + j + 1) / 2.0
        ranks[order[i : j + 1]] = avg_rank
        i = j + 1

    return ranks


def spearman_corr(x: np.ndarray, y: np.ndarray) -> float | None:
    """Spearman rank correlation between `x` and `y` (equal length, no scipy).

    Computed as the Pearson correlation of the average-rank-transformed
    arrays, which is the standard, exact definition of Spearman's rho
    (identical to scipy.stats.spearmanr's result for the same tie
    convention). Returns None when fewer than 2 points, or either array
    has zero rank variance (a constant array has undefined correlation).
    """
    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    if x.size != y.size:
        raise ValueError(f"length mismatch: {x.size} vs {y.size}")
    if x.size < 2:
        return None
    rx = _average_ranks(x)
    ry = _average_ranks(y)
    if np.std(rx) == 0.0 or np.std(ry) == 0.0:
        return None
    return float(np.corrcoef(rx, ry)[0, 1])


# ---------------------------------------------------------------------------
# Cross-regime comparison
# ---------------------------------------------------------------------------


def _symbol_set(q4: dict) -> set[str]:
    return {r["symbol"] for r in q4["symbols"]}


def _skip_fail_reason(q4: dict, symbol: str) -> str:
    """Look up why `symbol` is absent from a regime's successful q4 set.

    Checks that regime's own `skips` (below min_events) and `failures`
    (missing parquet / other exception) lists for a reason string. Falls
    back to a generic "absent, no reason recorded" if the symbol appears
    in neither list (e.g. it was never in that regime's requested
    universe at all).
    """
    for s in q4.get("skips", []):
        if s["symbol"] == symbol:
            return f"skipped below min_events (n_events={s.get('n_events', '?')})"
    for f in q4.get("failures", []):
        if f["symbol"] == symbol:
            return f"failed/missing ({f.get('reason', 'no reason recorded')})"
    return "absent from regime universe (no skip/failure record found)"


def _survivorship(baseline_q4: dict, regime_q4: dict) -> dict:
    """Baseline successful symbols minus this regime's successful symbols."""
    baseline_symbols = _symbol_set(baseline_q4)
    regime_symbols = _symbol_set(regime_q4)
    survivors = sorted(baseline_symbols & regime_symbols)
    non_survivors = sorted(baseline_symbols - regime_symbols)
    return {
        "n_baseline": len(baseline_symbols),
        "n_regime": len(regime_symbols),
        "n_survivors": len(survivors),
        "survivors": survivors,
        "non_survivors": [
            {"symbol": sym, "reason": _skip_fail_reason(regime_q4, sym)}
            for sym in non_survivors
        ],
    }


def _overlap_records(baseline_q4: dict, regime_q4: dict) -> tuple[list[dict], list[dict]]:
    """Per-symbol q4 records for the baseline and regime, restricted to the overlap, symbol-sorted identically."""
    baseline_by_symbol = {r["symbol"]: r for r in baseline_q4["symbols"]}
    regime_by_symbol = {r["symbol"]: r for r in regime_q4["symbols"]}
    overlap = sorted(set(baseline_by_symbol) & set(regime_by_symbol))
    return (
        [baseline_by_symbol[s] for s in overlap],
        [regime_by_symbol[s] for s in overlap],
    )


def _q6_overlap_alpha(baseline_q6: dict | None, regime_q6: dict | None) -> tuple[list[str], np.ndarray, np.ndarray] | None:
    if baseline_q6 is None or regime_q6 is None:
        return None
    baseline_by_symbol = {r["symbol"]: r["alpha_median"] for r in baseline_q6["records"]}
    regime_by_symbol = {r["symbol"]: r["alpha_median"] for r in regime_q6["records"]}
    overlap = sorted(set(baseline_by_symbol) & set(regime_by_symbol))
    if not overlap:
        return None
    base_arr = np.array([baseline_by_symbol[s] for s in overlap])
    regime_arr = np.array([regime_by_symbol[s] for s in overlap])
    return overlap, base_arr, regime_arr


def _regime_summary(q4: dict, q6: dict | None) -> dict:
    """Per-regime stats: n_success, recomputed regressions (+ mismatch warnings), medians/IQRs."""
    records = q4["symbols"]
    recomputed = _recompute_q4_regressions(records)
    gamma_mismatch = _reg_mismatch(
        recomputed["gamma_vs_activity"], q4.get("regressions", {}).get("gamma_vs_activity")
    )
    flip_mismatch = _reg_mismatch(
        recomputed["p_flip_vs_activity"], q4.get("regressions", {}).get("p_flip_vs_activity")
    )

    gamma_vals = np.array([r["gamma"] for r in records]) if records else np.array([])
    p_flip_vals = np.array([r["p_flip"] for r in records]) if records else np.array([])
    n_anti_persistent = int(np.sum(p_flip_vals > 0.5)) if records else 0

    summary = {
        "period": q4.get("period"),
        "n_success": len(records),
        "n_skipped": q4.get("n_symbols_skipped"),
        "n_failed": q4.get("n_symbols_failed"),
        "flip_law": recomputed["p_flip_vs_activity"],
        "flip_law_mismatch_warning": flip_mismatch,
        "gamma_law": recomputed["gamma_vs_activity"],
        "gamma_law_mismatch_warning": gamma_mismatch,
        "gamma_median": float(np.median(gamma_vals)) if gamma_vals.size else None,
        "gamma_iqr": (
            float(np.percentile(gamma_vals, 75) - np.percentile(gamma_vals, 25))
            if gamma_vals.size
            else None
        ),
        "p_flip_median": float(np.median(p_flip_vals)) if p_flip_vals.size else None,
        "n_anti_persistent": n_anti_persistent,
    }

    if q6 is not None:
        q6_records = q6["records"]
        recomputed_q6 = _recompute_q6_regression(q6_records)
        alpha_mismatch = _reg_mismatch(recomputed_q6, q6.get("activity_regression"))
        alpha_vals = np.array([r["alpha_median"] for r in q6_records]) if q6_records else np.array([])
        summary["alpha_law"] = recomputed_q6
        summary["alpha_law_mismatch_warning"] = alpha_mismatch
        summary["alpha_median"] = float(np.median(alpha_vals)) if alpha_vals.size else None
        summary["alpha_iqr"] = (
            float(np.percentile(alpha_vals, 75) - np.percentile(alpha_vals, 25))
            if alpha_vals.size
            else None
        )
    else:
        summary["alpha_law"] = None
        summary["alpha_law_mismatch_warning"] = None
        summary["alpha_median"] = None
        summary["alpha_iqr"] = None

    return summary


def _law_stability(baseline_summary: dict, regime_summaries: dict[str, dict]) -> dict:
    """Same-sign / slope-ratio / gamma-invariance verdicts across baseline + all regimes."""
    all_summaries = {"__baseline__": baseline_summary, **regime_summaries}

    flip_slopes = {
        label: s["flip_law"]["slope"] for label, s in all_summaries.items() if s["flip_law"] is not None
    }
    baseline_flip_slope = baseline_summary["flip_law"]["slope"] if baseline_summary["flip_law"] else None

    same_sign = None
    slope_ratios: dict[str, float | None] = {}
    if baseline_flip_slope is not None and baseline_flip_slope != 0.0 and flip_slopes:
        baseline_sign = np.sign(baseline_flip_slope)
        same_sign = all(np.sign(v) == baseline_sign for v in flip_slopes.values())
        for label, slope in flip_slopes.items():
            slope_ratios[label] = slope / baseline_flip_slope if label != "__baseline__" else 1.0

    gamma_r2_values = {
        label: s["gamma_law"]["r2"] for label, s in all_summaries.items() if s["gamma_law"] is not None
    }
    gamma_invariant = (
        all(r2 < GAMMA_FLAT_R2_THRESHOLD for r2 in gamma_r2_values.values())
        if gamma_r2_values
        else None
    )

    return {
        "flip_law_same_sign_all_regimes": same_sign,
        "flip_law_slope_by_label": {k: v for k, v in flip_slopes.items()},
        "flip_law_slope_ratio_vs_baseline": {k: v for k, v in slope_ratios.items() if k != "__baseline__"},
        "gamma_invariant_all_regimes": gamma_invariant,
        "gamma_r2_by_label": gamma_r2_values,
        "gamma_flat_r2_threshold": GAMMA_FLAT_R2_THRESHOLD,
    }


def _rank_correlations(
    baseline_q4: dict, baseline_q6: dict | None, regime_q4: dict, regime_q6: dict | None
) -> dict:
    """Spearman rho of p_flip, gamma (and alpha, if both sides have q6) on the symbol overlap."""
    base_records, regime_records = _overlap_records(baseline_q4, regime_q4)
    overlap_symbols = [r["symbol"] for r in base_records]

    result: dict = {"n_overlap": len(overlap_symbols), "symbols": overlap_symbols}

    if overlap_symbols:
        base_p_flip = np.array([r["p_flip"] for r in base_records])
        regime_p_flip = np.array([r["p_flip"] for r in regime_records])
        base_gamma = np.array([r["gamma"] for r in base_records])
        regime_gamma = np.array([r["gamma"] for r in regime_records])
        result["p_flip_spearman"] = spearman_corr(base_p_flip, regime_p_flip)
        result["gamma_spearman"] = spearman_corr(base_gamma, regime_gamma)
    else:
        result["p_flip_spearman"] = None
        result["gamma_spearman"] = None

    alpha_overlap = _q6_overlap_alpha(baseline_q6, regime_q6)
    if alpha_overlap is not None:
        symbols, base_alpha, regime_alpha = alpha_overlap
        result["alpha_n_overlap"] = len(symbols)
        result["alpha_spearman"] = spearman_corr(base_alpha, regime_alpha)
    else:
        result["alpha_n_overlap"] = 0
        result["alpha_spearman"] = None

    return result


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------


def _plot(
    out_dir: Path,
    baseline_label: str,
    baseline_q4: dict,
    regime_q4_by_label: dict[str, dict],
) -> None:
    fig, (ax_flip, ax_gamma, ax_scatter) = plt.subplots(1, 3, figsize=(19, 5.5))

    all_labeled_q4 = {baseline_label: baseline_q4, **regime_q4_by_label}
    colors = plt.cm.tab10(np.linspace(0, 1, max(len(all_labeled_q4), 1)))

    for (label, q4), color in zip(all_labeled_q4.items(), colors, strict=False):
        records = q4["symbols"]
        if not records:
            continue
        log_n = np.array([np.log10(r["n_events"]) for r in records])
        p_flip = np.array([r["p_flip"] for r in records])
        gamma = np.array([r["gamma"] for r in records])

        ax_flip.scatter(log_n, p_flip, s=18, alpha=0.6, color=color, label=label)
        reg = _ols_with_intercept(log_n, p_flip)
        if reg is not None:
            x_line = np.array([log_n.min(), log_n.max()])
            ax_flip.plot(x_line, reg["slope"] * x_line + reg["intercept"], color=color, linewidth=1.5)

        ax_gamma.scatter(log_n, gamma, s=18, alpha=0.6, color=color, label=label)
        reg_g = _ols_with_intercept(log_n, gamma)
        if reg_g is not None:
            x_line = np.array([log_n.min(), log_n.max()])
            ax_gamma.plot(x_line, reg_g["slope"] * x_line + reg_g["intercept"], color=color, linewidth=1.5)

    ax_flip.axhline(0.5, color="gray", linestyle="--", linewidth=1.0)
    ax_flip.set_xlabel("log10(n_events)")
    ax_flip.set_ylabel(r"$p_{flip}$")
    ax_flip.set_title("Flip law across regimes")
    ax_flip.legend(fontsize=8)

    ax_gamma.set_xlabel("log10(n_events)")
    ax_gamma.set_ylabel(r"$\hat{\gamma}$")
    ax_gamma.set_title(r"$\gamma$ vs. activity across regimes")
    ax_gamma.legend(fontsize=8)

    # Symbol-level scatter: baseline p_flip vs. the first regime's p_flip.
    if regime_q4_by_label:
        first_label = next(iter(regime_q4_by_label))
        base_records, regime_records = _overlap_records(baseline_q4, regime_q4_by_label[first_label])
        if base_records:
            base_p_flip = np.array([r["p_flip"] for r in base_records])
            regime_p_flip = np.array([r["p_flip"] for r in regime_records])
            ax_scatter.scatter(base_p_flip, regime_p_flip, s=24, alpha=0.7)
            lo = float(min(base_p_flip.min(), regime_p_flip.min(), 0.0))
            hi = float(max(base_p_flip.max(), regime_p_flip.max(), 1.0))
            ax_scatter.plot([lo, hi], [lo, hi], color="gray", linestyle="--", linewidth=1.0, label="y = x")
            ax_scatter.legend()
        ax_scatter.set_xlabel(f"p_flip ({baseline_label})")
        ax_scatter.set_ylabel(f"p_flip ({first_label})")
        ax_scatter.set_title(f"Symbol-level p_flip: {baseline_label} vs. {first_label}")
    else:
        ax_scatter.set_title("Symbol-level p_flip scatter (no regimes provided)")

    fig.tight_layout()
    fig.savefig(out_dir / "q8_regimes.png", dpi=150, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Markdown report
# ---------------------------------------------------------------------------


def _fmt_reg(reg: dict | None) -> str:
    if reg is None:
        return "not estimable (fewer than 3 successful symbols, or zero variance in log10(n_events))"
    return (
        f"slope = **{reg['slope']:.4f}** (stderr {reg['stderr']:.4f}), "
        f"intercept = {reg['intercept']:.4f}, R² = {reg['r2']:.4f}, n = {reg['n']}"
    )


def _fmt_corr(rho: float | None) -> str:
    return "n/a" if rho is None else f"{rho:.4f}"


def _write_md(
    out_dir: Path,
    baseline_label: str,
    baseline_summary: dict,
    regime_summaries: dict[str, dict],
    survivorship_by_label: dict[str, dict],
    rank_corr_by_label: dict[str, dict],
    law_stability: dict,
) -> None:
    lines: list[str] = []
    lines.append("# Q8: regime comparator — temporal robustness of the cross-sectional laws")
    lines.append("")
    lines.append("## Methodology")
    lines.append("")
    lines.append(
        f"Loads `q4_cross_section.json` (required) and `q6_endogeneity.json` (optional — not "
        "every regime necessarily has a Q6 run) from a baseline directory "
        f"(`{baseline_label}`) and one or more regime directories. Every cross-sectional "
        "regression (γ̂ vs. log10(activity), p_flip vs. log10(activity), and α̂_median vs. "
        "log10(activity) when Q6 is present) is **recomputed from the per-symbol records "
        "using this module's own `np.polyfit`-based OLS** — the upstream jsons' stored "
        "`regressions` / `activity_regression` blocks are never trusted directly, only "
        "cross-checked against the recomputed values; any mismatch beyond a tight numerical "
        f"tolerance ({REGRESSION_MISMATCH_TOL:g}) is reported as an explicit warning below "
        "rather than silently accepted or overwritten."
    )
    lines.append("")
    lines.append(
        "**Survivorship**: for each regime, the baseline's successful symbol set is compared "
        "against that regime's successful symbol set. Baseline symbols absent from a regime "
        "are non-survivors; each is annotated with a reason drawn from that regime's own Q4 "
        "`skips` (below `min_events`) and `failures` (missing parquet / other exception) "
        "lists when available, distinguishing symbols that simply fell below the activity "
        "threshold in that regime from symbols that failed or are missing outright."
    )
    lines.append("")
    lines.append(
        "**Rank correlation**: Spearman's rho on the symbol overlap for p_flip, γ̂ (and α̂ "
        "when both sides have a Q6 run), computed via average-rank ranking (ties share the "
        "mean of their ranks) and Pearson correlation of the ranks — the standard exact "
        "definition of Spearman's rho, implemented with numpy only (no scipy dependency)."
    )
    lines.append("")
    lines.append(
        "**Law-stability verdicts**: same-sign check on the flip-law slope across baseline "
        "and every regime; slope ratio of each regime vs. baseline; γ-invariance is verdicted "
        f"true iff EVERY regime's (baseline included) γ-vs-activity R² falls below "
        f"{GAMMA_FLAT_R2_THRESHOLD:g}. All verdict text below is generated from these computed "
        "values — the wording is not hardcoded to a particular conclusion; either the law "
        "holds or it does not, and this report states whichever the data shows."
    )
    lines.append("")

    lines.append("## Regime table")
    lines.append("")
    lines.append(
        "| regime | n_success | flip slope | flip R² | γ slope | γ R² | γ median (IQR) | "
        "p_flip median | anti-persistent | α median (IQR) |"
    )
    lines.append("|---|---|---|---|---|---|---|---|---|---|")

    def _row(label: str, s: dict) -> str:
        flip = s["flip_law"]
        gamma = s["gamma_law"]
        flip_slope = f"{flip['slope']:.4f}" if flip else "n/a"
        flip_r2 = f"{flip['r2']:.4f}" if flip else "n/a"
        gamma_slope = f"{gamma['slope']:.4f}" if gamma else "n/a"
        gamma_r2 = f"{gamma['r2']:.4f}" if gamma else "n/a"
        gamma_med = (
            f"{s['gamma_median']:.4f} ({s['gamma_iqr']:.4f})" if s["gamma_median"] is not None else "n/a"
        )
        p_flip_med = f"{s['p_flip_median']:.4f}" if s["p_flip_median"] is not None else "n/a"
        alpha_med = (
            f"{s['alpha_median']:.4f} ({s['alpha_iqr']:.4f})" if s["alpha_median"] is not None else "n/a"
        )
        return (
            f"| {label} | {s['n_success']} | {flip_slope} | {flip_r2} | {gamma_slope} | "
            f"{gamma_r2} | {gamma_med} | {p_flip_med} | {s['n_anti_persistent']} | {alpha_med} |"
        )

    lines.append(_row(baseline_label, baseline_summary))
    for label, s in regime_summaries.items():
        lines.append(_row(label, s))
    lines.append("")

    warnings = []
    for label, s in {"__baseline__": baseline_summary, **regime_summaries}.items():
        display = baseline_label if label == "__baseline__" else label
        for key in ("flip_law_mismatch_warning", "gamma_law_mismatch_warning", "alpha_law_mismatch_warning"):
            w = s.get(key)
            if w:
                warnings.append(f"- **{display}** ({key}): {w}")
    if warnings:
        lines.append("## Regression cross-check warnings")
        lines.append("")
        lines.append(
            "The following recomputed regressions disagreed with the stored json's own "
            "regression block beyond tolerance:"
        )
        lines.append("")
        lines.extend(warnings)
        lines.append("")

    lines.append("## Law-stability verdicts")
    lines.append("")
    same_sign = law_stability["flip_law_same_sign_all_regimes"]
    if same_sign is None:
        lines.append(
            "**Flip-law sign stability**: not evaluable (baseline flip-law slope is not "
            "estimable, zero, or no regime has an estimable flip-law slope)."
        )
    elif same_sign:
        lines.append(
            "**Flip-law sign stability**: the flip-law slope has the **same sign** in every "
            "regime as in the baseline — the direction of the p_flip-vs-activity relationship "
            "is stable across regimes."
        )
    else:
        flipped = [
            label
            for label, slope in law_stability["flip_law_slope_by_label"].items()
            if label != "__baseline__"
            and np.sign(slope) != np.sign(law_stability["flip_law_slope_by_label"]["__baseline__"])
        ]
        lines.append(
            "**Flip-law sign stability**: the flip-law slope **changes sign** relative to the "
            f"baseline in at least one regime ({', '.join(flipped) if flipped else 'see table'}) "
            "— the direction of the p_flip-vs-activity relationship does NOT hold across "
            "regimes."
        )
    lines.append("")

    ratios = law_stability["flip_law_slope_ratio_vs_baseline"]
    if ratios:
        lines.append("Flip-law slope ratio vs. baseline, per regime:")
        lines.append("")
        for label, ratio in ratios.items():
            lines.append(f"- {label}: {ratio:.4f}x baseline slope" if ratio is not None else f"- {label}: n/a")
        lines.append("")

    gamma_inv = law_stability["gamma_invariant_all_regimes"]
    if gamma_inv is None:
        lines.append(
            "**γ invariance**: not evaluable (no regime has an estimable γ-vs-activity "
            "regression)."
        )
    elif gamma_inv:
        lines.append(
            f"**γ invariance**: every regime's γ-vs-activity R² is below "
            f"{GAMMA_FLAT_R2_THRESHOLD:g} — γ shows **no detectable activity dependence in any "
            "regime**, consistent with the liquidity-invariance finding holding across time."
        )
    else:
        above = [
            label for label, r2 in law_stability["gamma_r2_by_label"].items() if r2 >= GAMMA_FLAT_R2_THRESHOLD
        ]
        lines.append(
            f"**γ invariance**: at least one regime's γ-vs-activity R² is at or above "
            f"{GAMMA_FLAT_R2_THRESHOLD:g} ({', '.join(above)}) — γ's liquidity-invariance does "
            "**not** hold uniformly across every regime examined here."
        )
    lines.append("")

    lines.append("## Survivorship")
    lines.append("")
    for label, surv in survivorship_by_label.items():
        lines.append(
            f"**{label}**: {surv['n_survivors']}/{surv['n_baseline']} baseline symbols survive "
            f"into this regime's successful set ({surv['n_regime']} symbols total in this "
            f"regime). {len(surv['non_survivors'])} non-survivor(s)."
        )
        lines.append("")
        if surv["non_survivors"]:
            lines.append("| symbol | reason |")
            lines.append("|---|---|")
            for ns in surv["non_survivors"]:
                lines.append(f"| {ns['symbol']} | {ns['reason']} |")
            lines.append("")

    lines.append("## Symbol-level rank correlation")
    lines.append("")
    lines.append("| regime | n overlap | p_flip Spearman ρ | γ Spearman ρ | α overlap n | α Spearman ρ |")
    lines.append("|---|---|---|---|---|---|")
    for label, rc in rank_corr_by_label.items():
        lines.append(
            f"| {label} | {rc['n_overlap']} | {_fmt_corr(rc['p_flip_spearman'])} | "
            f"{_fmt_corr(rc['gamma_spearman'])} | {rc['alpha_n_overlap']} | "
            f"{_fmt_corr(rc['alpha_spearman'])} |"
        )
    lines.append("")

    lines.append("## Caveats")
    lines.append("")
    lines.append(
        "- **`min_events` filter shifts membership across regimes**: a symbol's activity "
        "level in a given month determines whether it clears the Q4 `min_events` threshold "
        "at all, so the 'successful' symbol set is not the same fixed panel across regimes — "
        "some non-survivors are genuinely below the activity bar in that regime, not "
        "delisted or otherwise absent, and this is reported as such via the skip/failure "
        "reason above rather than conflated with true delistings."
    )
    lines.append(
        "- **The regime universe is fixed to the baseline symbol list**: any symbol newly "
        "listed in a later regime but absent from the baseline period is deliberately "
        "excluded from every regime's requested universe upstream (Q4/Q6 are run against "
        "`results/universe_2023-06.txt`), to keep the panel fixed and comparable across "
        "regimes — this survivorship analysis therefore cannot and does not speak to new "
        "listings, only to the fate of the original panel."
    )
    lines.append(
        "- **Regression stderr/R² inherit Q4/Q6's own heteroskedasticity caveat**: as "
        "documented in `q4_cross_section.md` and `q6_endogeneity.md`, per-symbol estimator "
        "noise is not uniform across the cross-section, so the OLS regressions recomputed "
        "here (same assumptions, same caveat) should be read descriptively, not as formal "
        "confidence intervals."
    )
    lines.append(
        "- **Spearman rho on a possibly small overlap**: rank correlation is only as "
        "informative as the overlap size allows; a small `n_overlap` (see the table above) "
        "should be weighted accordingly rather than treated as a precise correlation "
        "estimate."
    )
    lines.append("")

    (out_dir / "q8_regimes.md").write_text("\n".join(lines))


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def run_q8(
    out_dir: Path,
    baseline_dir: Path,
    regime_dirs: dict[str, Path],
    baseline_label: str = "2023-06",
) -> dict:
    """Compare the Q4/Q6 cross-sectional laws between a baseline period and one or more regimes.

    `regime_dirs` maps a display label (e.g. "2023-07", "2026-07") to the
    directory holding that regime's q4_cross_section.json (+ optional
    q6_endogeneity.json). Reads only those two json files per directory —
    never touches `data/` or any raw parquet.
    """
    out_dir.mkdir(parents=True, exist_ok=True)

    baseline = _load_regime(baseline_dir)
    regimes = {label: _load_regime(path) for label, path in regime_dirs.items()}

    baseline_summary = _regime_summary(baseline["q4"], baseline["q6"])
    regime_summaries = {
        label: _regime_summary(r["q4"], r["q6"]) for label, r in regimes.items()
    }

    survivorship_by_label = {
        label: _survivorship(baseline["q4"], r["q4"]) for label, r in regimes.items()
    }

    rank_corr_by_label = {
        label: _rank_correlations(baseline["q4"], baseline["q6"], r["q4"], r["q6"])
        for label, r in regimes.items()
    }

    law_stability = _law_stability(baseline_summary, regime_summaries)

    result = {
        "baseline_label": baseline_label,
        "regime_labels": list(regime_dirs.keys()),
        "baseline_summary": baseline_summary,
        "regime_summaries": regime_summaries,
        "survivorship": survivorship_by_label,
        "rank_correlations": rank_corr_by_label,
        "law_stability": law_stability,
    }

    _plot(out_dir, baseline_label, baseline["q4"], {label: r["q4"] for label, r in regimes.items()})
    _write_md(
        out_dir,
        baseline_label,
        baseline_summary,
        regime_summaries,
        survivorship_by_label,
        rank_corr_by_label,
        law_stability,
    )
    (out_dir / "q8_regimes.json").write_text(json.dumps(result, indent=2))
    return result


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Q8: regime comparator")
    parser.add_argument("--out", type=Path, default=Path("results"))
    parser.add_argument("--baseline-dir", type=Path, required=True)
    parser.add_argument("--baseline-label", type=str, default="2023-06")
    parser.add_argument(
        "--regime",
        action="append",
        default=[],
        metavar="LABEL=DIR",
        help="a regime directory as LABEL=DIR; repeatable",
    )
    return parser.parse_args(argv)


def _parse_regime_args(regime_args: list[str]) -> dict[str, Path]:
    regime_dirs: dict[str, Path] = {}
    for entry in regime_args:
        if "=" not in entry:
            raise ValueError(f"--regime must be LABEL=DIR, got: {entry!r}")
        label, _, dir_str = entry.partition("=")
        regime_dirs[label] = Path(dir_str)
    return regime_dirs


if __name__ == "__main__":
    args = _parse_args()
    run_q8(
        args.out,
        baseline_dir=args.baseline_dir,
        regime_dirs=_parse_regime_args(args.regime),
        baseline_label=args.baseline_label,
    )
