"""Synthetic ground-truth tests for the Hawkes toolkit.

These tests ARE the deliverable for Phase-3 Task 1: the simulator, the
exponential-kernel MLE, and the model-free count-variance branching
estimator are only trustworthy insofar as they recover known parameters
on data generated by the simulator itself (and, for the trap test, on
data generated by a process that is deliberately NOT Hawkes).
"""
from __future__ import annotations

import numpy as np
import pytest

from microstructure.estimators.hawkes import (
    HawkesFit,
    MultiExpFit,
    _nelder_mead,
    branching_count_variance,
    branching_ratio_sensitivity,
    fit_hawkes_exp,
    fit_hawkes_multiexp,
    hawkes_loglik,
    simulate_hawkes_exp,
    simulate_hawkes_multiexp,
    simulate_seasonal_hawkes_exp,
)

# ---------------------------------------------------------------------------
# Group 0: Nelder-Mead sanity check on a known quadratic (test the optimizer
# itself before trusting it to fit anything statistical).
# ---------------------------------------------------------------------------


def test_nelder_mead_recovers_quadratic_minimum():
    # f(x, y) = (x - 3)^2 + (y + 2)^2 + 7, minimum at (3, -2), f_min = 7.
    def f(p: np.ndarray) -> float:
        return float((p[0] - 3.0) ** 2 + (p[1] + 2.0) ** 2 + 7.0)

    x0 = np.array([0.0, 0.0])
    best_x, best_f, converged = _nelder_mead(f, x0, max_iter=500)
    assert converged
    assert abs(best_x[0] - 3.0) < 1e-3
    assert abs(best_x[1] - (-2.0)) < 1e-3
    assert abs(best_f - 7.0) < 1e-5


def test_nelder_mead_handles_rosenbrock_like_valley():
    # A harder, curved-valley function: minimum at (1, 1), f_min = 0.
    def f(p: np.ndarray) -> float:
        x, y = p
        return float(100.0 * (y - x**2) ** 2 + (1.0 - x) ** 2)

    x0 = np.array([-1.0, 1.5])
    best_x, best_f, _converged = _nelder_mead(f, x0, max_iter=2000)
    assert best_f < 1e-3
    assert abs(best_x[0] - 1.0) < 0.05
    assert abs(best_x[1] - 1.0) < 0.05


# ---------------------------------------------------------------------------
# Group 0b: log-likelihood formula verified against numerical integration
# of the intensity on a tiny hand-checkable case.
# ---------------------------------------------------------------------------


def test_loglik_matches_numerical_intensity_integration():
    """Verify Σ log λ(t_i) − ∫λ(t)dt against brute-force numerical intensity.

    Uses 10 fixed event times (not simulated) so the check is independent
    of the simulator. Integrates λ(t) = mu + Σ alpha*beta*exp(-beta(t-t_i))
    with a fine trapezoid rule over [0, T] and compares to the closed-form
    recursion used in hawkes_loglik.
    """
    times = np.array([1.0, 1.3, 2.1, 2.15, 3.0, 4.4, 4.5, 4.55, 6.0, 8.0])
    t_end = 10.0
    mu, alpha, beta = 0.3, 0.5, 1.5

    ll_closed = hawkes_loglik(times, t_end, mu, alpha, beta)

    # Brute-force: Σ log λ(t_i^-) exactly (no integration needed for the
    # sum term — λ just before each event, using only prior events).
    log_sum = 0.0
    for i, ti in enumerate(times):
        prior = times[:i]
        excitation = np.sum(alpha * beta * np.exp(-beta * (ti - prior))) if i > 0 else 0.0
        log_sum += np.log(mu + excitation)

    # Numerically integrate the compensator ∫_0^T λ(t) dt via fine trapezoid.
    grid = np.linspace(0.0, t_end, 2_000_000)
    excitation_grid = np.zeros_like(grid)
    for ti in times:
        mask = grid > ti
        excitation_grid[mask] += alpha * beta * np.exp(-beta * (grid[mask] - ti))
    lam_grid = mu + excitation_grid
    compensator_numeric = np.trapezoid(lam_grid, grid)

    ll_numeric = log_sum - compensator_numeric

    assert abs(ll_closed - ll_numeric) < 1e-3, (ll_closed, ll_numeric)


# ---------------------------------------------------------------------------
# Group 0c: simulate_hawkes_exp must reject explosive/invalid parameters at
# entry rather than hang. alpha >= 1 makes the branching ratio >= 1, so the
# expected number of descendants per event is infinite/non-convergent and
# Ogata thinning's while loop (bounded by t_end but driven by ever-growing
# excitation) never reaches t_end in finite time/memory. Verified: alpha=1.5
# never terminates without this guard.
# ---------------------------------------------------------------------------


def test_simulate_rejects_alpha_at_or_above_one():
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 1.0, 2.0, 1000.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 1.5, 2.0, 1000.0, seed=1)


def test_simulate_rejects_negative_alpha():
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, -0.1, 2.0, 1000.0, seed=1)


def test_simulate_rejects_non_positive_mu():
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.0, 0.4, 2.0, 1000.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_exp(-0.1, 0.4, 2.0, 1000.0, seed=1)


def test_simulate_rejects_non_positive_beta():
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 0.4, 0.0, 1000.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 0.4, -1.0, 1000.0, seed=1)


def test_simulate_rejects_non_positive_t_end():
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 0.4, 2.0, 0.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_exp(0.5, 0.4, 2.0, -100.0, seed=1)


# ---------------------------------------------------------------------------
# Group 1: simulate -> fit round trip across 3 seeds.
# ---------------------------------------------------------------------------

TRUE_MU, TRUE_ALPHA, TRUE_BETA = 0.5, 0.4, 2.0
T_END = 200_000.0
FIT_SUBSAMPLE_T = 100_000.0  # per brief: subsample fit tests to first 100k events' worth


def _simulate_and_fit(seed: int) -> tuple[np.ndarray, HawkesFit]:
    times = simulate_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, seed=seed)
    # Subsample to the first FIT_SUBSAMPLE_T seconds of events for MLE speed
    # (full sims are 150-300k events; fitting on ~half keeps the whole
    # suite under the runtime budget while still exercising the estimator
    # at realistic sample size, per the brief's runtime-discipline note).
    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    return times, fit


@pytest.mark.parametrize("seed", [7, 8, 9])
def test_mle_recovers_known_parameters(seed):
    _, fit = _simulate_and_fit(seed)
    assert fit.converged
    assert abs(fit.alpha - TRUE_ALPHA) < 0.03, f"seed={seed} alpha={fit.alpha}"
    assert abs(fit.mu - TRUE_MU) < 0.05, f"seed={seed} mu={fit.mu}"
    assert abs(fit.beta - TRUE_BETA) / TRUE_BETA < 0.20, f"seed={seed} beta={fit.beta}"


def test_mle_alpha_stable_across_seeds():
    alphas = []
    for seed in (7, 8, 9):
        _, fit = _simulate_and_fit(seed)
        alphas.append(fit.alpha)
    sd = float(np.std(alphas, ddof=1))
    assert sd < 0.02, f"alphas={alphas} sd={sd}"


# ---------------------------------------------------------------------------
# Group 2: count-variance estimator on the same simulations.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("seed", [7, 8, 9])
def test_count_variance_recovers_branching_ratio(seed):
    times = simulate_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, seed=seed)
    n_hat = branching_count_variance(times, window=500.0, t_end=T_END)
    assert abs(n_hat - TRUE_ALPHA) < 0.05, f"seed={seed} n_hat={n_hat}"


def test_count_variance_guards_too_few_windows():
    times = np.array([1.0, 2.0, 3.0])
    with pytest.raises(ValueError):
        branching_count_variance(times, window=1.0, t_end=3.0)


def test_count_variance_guards_zero_variance():
    # Perfectly regular spacing (one event every 1.0s) with window=10.0
    # puts exactly 10 events in every non-overlapping window -> var == 0.
    times = np.arange(0.0, 10_000.0, 1.0)
    with pytest.raises(ValueError):
        branching_count_variance(times, window=10.0, t_end=10_000.0)


# ---------------------------------------------------------------------------
# Group 3: near-critical regime (alpha=0.85) — wider tolerances, documented.
# ---------------------------------------------------------------------------

NEAR_CRITICAL_ALPHA = 0.85


def test_near_critical_mle_recovers_within_widened_tolerance():
    """Near n=1, mu/alpha become weakly identified locally (docs/research/02 §4
    pitfall 5: 'near-unidentifiability at n≈1'); we widen tolerances vs the
    n=0.4 case rather than pretend the estimator is equally sharp everywhere.
    """
    times = simulate_hawkes_exp(TRUE_MU, NEAR_CRITICAL_ALPHA, TRUE_BETA, T_END, seed=11)
    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert abs(fit.alpha - NEAR_CRITICAL_ALPHA) < 0.08, f"alpha={fit.alpha}"
    assert abs(fit.mu - TRUE_MU) < 0.15, f"mu={fit.mu}"

    n_hat = branching_count_variance(times, window=500.0, t_end=T_END)
    assert abs(n_hat - NEAR_CRITICAL_ALPHA) < 0.12, f"n_hat={n_hat}"


# ---------------------------------------------------------------------------
# Group 4: Poisson refutation test (the Filimonov-Sornette trap).
# ---------------------------------------------------------------------------


def test_poisson_refutation_both_estimators_report_near_zero():
    """A pure Poisson stream (alpha=0) must NOT look self-exciting.

    Note: we only assert on fit.alpha here, not fit.beta. When the true
    process has no self-excitation, beta (the kernel decay rate) is
    unidentified/degenerate at alpha=0 — there's no kernel timescale to
    recover, since the excitation term alpha*beta*R_i vanishes regardless
    of beta once alpha->0. The MLE surface is essentially flat in beta at
    that point, so a fitted beta value is not meaningful evidence of
    anything here and correctly is not asserted on.
    """
    rng = np.random.default_rng(21)
    rate = 1.0
    t_end = 200_000.0
    n_expected = int(rate * t_end * 1.05)
    gaps = rng.exponential(1.0 / rate, size=n_expected)
    times = np.cumsum(gaps)
    times = times[times <= t_end]

    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert fit.alpha < 0.05, f"fitted alpha={fit.alpha} on pure Poisson"

    n_hat = branching_count_variance(times, window=500.0, t_end=t_end)
    assert n_hat < 0.05, f"count-variance n_hat={n_hat} on pure Poisson"


def test_regime_switching_poisson_produces_spurious_endogeneity_trap():
    """THE TRAP (Filimonov & Sornette 2015, docs/research/02-hawkes-processes.md,
    'The calibration counterattack' section, §2.4-equivalent discussion):
    n̂ ≈ near-critical can be MANUFACTURED FROM NOTHING. Fitting a Hawkes
    model (or the count-variance estimator) to a regime-switching Poisson
    process — no self-excitation anywhere, only a rate that alternates
    between a low and a high value on a fixed clock — produces a SPURIOUS
    positive branching-ratio estimate, because clustering induced by rate
    non-stationarity is statistically indistinguishable, to both a
    likelihood fit and a count-mean/variance test, from clustering induced
    by genuine self-excitation.

    This is why deseasonalization (fitting or removing a time-varying
    baseline mu(t) BEFORE testing for endogeneity) is not optional: any
    Hawkes/branching-ratio estimate computed on a non-stationary-rate
    series conflates "the rate changes over time" with "events cause more
    events," and the two are observationally similar in aggregate count
    statistics. We assert n_hat > 0.2 for count-variance and fitted
    alpha > 0.5 for the MLE here specifically to document that the
    spurious effect is not a rounding error in either estimator — it is
    large enough, in both, to be mistaken for real, moderate-to-severe
    endogeneity.
    """
    rng = np.random.default_rng(22)
    low_rate, high_rate = 0.5, 2.0
    regime_len = 5000.0
    t_end = 200_000.0

    times: list[float] = []
    t = 0.0
    regime_start = 0.0
    is_low = True
    while regime_start < t_end:
        rate = low_rate if is_low else high_rate
        regime_end = min(regime_start + regime_len, t_end)
        t = regime_start
        while True:
            t += rng.exponential(1.0 / rate)
            if t >= regime_end:
                break
            times.append(t)
        regime_start = regime_end
        is_low = not is_low

    times_arr = np.asarray(times, dtype=np.float64)

    n_hat = branching_count_variance(times_arr, window=500.0, t_end=t_end)
    assert n_hat > 0.2, (
        f"expected the regime-switching trap to produce spurious n_hat > 0.2, "
        f"got {n_hat}"
    )

    fit_times = times_arr[times_arr <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert fit.alpha > 0.5, (
        f"expected the regime-switching trap to also fool the MLE with "
        f"fitted alpha > 0.5, got {fit.alpha}"
    )


# ---------------------------------------------------------------------------
# Group 5: simulate_seasonal_hawkes_exp (Phase-3 Task 2 rebuild) — a Hawkes
# process with a genuinely time-varying (periodic, piecewise-constant)
# baseline rate, for testing business-time rescaling against a real
# generative model rather than a post-hoc-thinned approximation.
# ---------------------------------------------------------------------------


def test_simulate_seasonal_rejects_invalid_parameters():
    flat_shape = np.ones(48)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.0, 0.4, 2.0, 1000.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(-0.1, 0.4, 2.0, 1000.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.5, -0.1, 2.0, 1000.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.5, 1.0, 2.0, 1000.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.5, 0.4, 0.0, 1000.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, 0.0, flat_shape, seed=1)
    with pytest.raises(ValueError):
        simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, 1000.0, np.array([]), seed=1)
    with pytest.raises(ValueError):
        # non-positive entry in shape
        bad_shape = np.ones(48)
        bad_shape[3] = 0.0
        simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, 1000.0, bad_shape, seed=1)
    with pytest.raises(ValueError):
        # non-finite entry in shape
        bad_shape = np.ones(48)
        bad_shape[3] = np.nan
        simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, 1000.0, bad_shape, seed=1)


def test_simulate_seasonal_stationary_shape_recovers_known_parameters():
    """Sanity: a flat (mean-1) shape gives no seasonal confound, so a fit on
    the seasonal simulator's output should recover parameters just as well
    as the unseasonal simulator does (Group 1's tolerances)."""
    flat_shape = np.ones(48)
    times = simulate_seasonal_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, flat_shape, seed=7)
    fit_times = times[times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert fit.converged
    assert abs(fit.alpha - TRUE_ALPHA) < 0.05, f"alpha={fit.alpha}"
    assert abs(fit.mu - TRUE_MU) < 0.08, f"mu={fit.mu}"


def test_simulate_seasonal_reduces_to_unseasonal_statistically():
    """With shape≡1, the seasonal simulator's output should be statistically
    indistinguishable (matched event count and fitted-parameter ballpark)
    from `simulate_hawkes_exp` on the same parameters -- not the same exact
    event times (the acceptance draws differ once lambda_bar's composition
    differs), but the same underlying distribution."""
    flat_shape = np.ones(48)
    seasonal_times = simulate_seasonal_hawkes_exp(
        TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, flat_shape, seed=7
    )
    unseasonal_times = simulate_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, seed=7)

    # Event counts should be close (same Poisson-driven rate structure);
    # allow a generous relative tolerance since seeds drive different
    # candidate-acceptance sequences.
    rel_diff = abs(seasonal_times.size - unseasonal_times.size) / unseasonal_times.size
    assert rel_diff < 0.05, (
        f"seasonal n={seasonal_times.size} vs unseasonal n={unseasonal_times.size}, "
        f"rel_diff={rel_diff}"
    )

    fit_times = seasonal_times[seasonal_times <= FIT_SUBSAMPLE_T]
    fit = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    assert abs(fit.alpha - TRUE_ALPHA) < 0.05, f"alpha={fit.alpha}"


# ---------------------------------------------------------------------------
# Group 6: sum-of-exponentials Hawkes kernel (K-sensitivity of n̂).
#
# The whole point of this group (docs/research/02-hawkes-processes.md §4
# pitfall 3): "Exponential fits to power-law data underestimate n; ...
# Fit sums of exponentials spanning decades of timescales; check n̂
# stability." A K=1 fit on data generated by a genuinely 2-timescale kernel
# should UNDERESTIMATE the true branching ratio; a K=2 fit should recover
# it; a K=3 fit (over-parameterized relative to the truth) should still be
# in the right ballpark without blowing up. This directly probes the
# project's headline 41/41-symbol exp-MLE-vs-count-variance disagreement.
#
# CRITICAL CAVEAT tested at the end of this group
# (`test_seasonal_baseline_confound_mimics_long_memory`): the K=1->K=2 n̂
# rise / slow-component signature used above as evidence of genuine long
# memory is NOT unique to long memory. Residual baseline non-stationarity
# (imperfect deseasonalization, regime changes) produces the identical
# numerical signature in a process with NO long memory at all -- n̂(K)
# alone cannot tell the two apart. See that test's and
# `fit_hawkes_multiexp`'s docstrings for the diagnostic (compare the slow
# component's timescale to the deseasonalization bin width / fit-window
# length) and the control (re-fit K=1 with a block-wise-constant baseline).
# ---------------------------------------------------------------------------

# Planted 2-exponential kernel: alpha=(0.25, 0.35) [n=0.6], beta=(5, 0.2)
# (one fast/short-memory component, one slow/long-memory component spanning
# a full decade apart -- beta=5 has timescale 1/5=0.2, beta=0.2 has
# timescale 1/0.2=5, a 25x separation).
PLANTED_MU = 0.5
PLANTED_ALPHAS = np.array([0.25, 0.35])
PLANTED_BETAS = np.array([5.0, 0.2])
PLANTED_N = float(PLANTED_ALPHAS.sum())  # 0.6
# mean_rate ~ mu/(1-n) = 0.5/0.4 = 1.25/unit time; t_end=48_000 gives ~60k events.
PLANTED_T_END = 48_000.0


def test_multiexp_k1_matches_fit_hawkes_exp():
    """K=1 must reproduce fit_hawkes_exp on the same data.

    With one component, the alpha-logit softmax-with-slack-slot reduces
    exactly to the logistic map fit_hawkes_exp itself uses, so the two
    optimizers are searching the same reparameterized likelihood surface --
    they should land on (numerically) the same optimum.
    """
    times = simulate_hawkes_exp(TRUE_MU, TRUE_ALPHA, TRUE_BETA, T_END, seed=7)
    fit_times = times[times <= FIT_SUBSAMPLE_T]

    single = fit_hawkes_exp(fit_times, FIT_SUBSAMPLE_T)
    multi = fit_hawkes_multiexp(fit_times, FIT_SUBSAMPLE_T, K=1)

    assert multi.K == 1
    assert multi.alphas.shape == (1,)
    assert multi.betas.shape == (1,)
    # The two fits run independent Nelder-Mead searches (different simplex
    # paths, including different multi-start beta seeds) over the SAME
    # reparameterized likelihood, so they converge to the same optimum only
    # up to each optimizer's own tol=1e-6 loglik-spread stopping criterion,
    # not to bit-identical parameters. Measured on this dataset: loglik
    # agrees to ~1e-7, mu/alpha to ~1e-6/1e-7, beta (the flattest direction
    # near this optimum) to ~3e-5. Tolerances below (loglik 1e-5, mu/alpha
    # 1e-5, beta 1e-4) leave comfortable headroom above those measured
    # diffs while still being tight enough to demonstrate the two code paths
    # are mathematically identical, not simply "close enough."
    assert abs(multi.mu - single.mu) < 1e-5, (multi.mu, single.mu)
    assert abs(multi.alphas[0] - single.alpha) < 1e-5, (multi.alphas[0], single.alpha)
    assert abs(multi.betas[0] - single.beta) < 1e-4, (multi.betas[0], single.beta)
    assert abs(multi.n - single.alpha) < 1e-5
    assert abs(multi.loglik - single.loglik) < 1e-5, (multi.loglik, single.loglik)


def test_simulate_multiexp_rejects_invalid_parameters():
    with pytest.raises(ValueError):
        simulate_hawkes_multiexp(0.0, PLANTED_ALPHAS, PLANTED_BETAS, 1000.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_multiexp(-0.1, PLANTED_ALPHAS, PLANTED_BETAS, 1000.0, seed=1)
    with pytest.raises(ValueError):
        simulate_hawkes_multiexp(0.5, PLANTED_ALPHAS, PLANTED_BETAS, 0.0, seed=1)
    with pytest.raises(ValueError):
        # mismatched lengths
        simulate_hawkes_multiexp(0.5, np.array([0.3, 0.3]), np.array([1.0]), 1000.0, seed=1)
    with pytest.raises(ValueError):
        # negative beta
        simulate_hawkes_multiexp(0.5, np.array([0.3]), np.array([-1.0]), 1000.0, seed=1)
    with pytest.raises(ValueError):
        # negative alpha
        simulate_hawkes_multiexp(0.5, np.array([-0.1]), np.array([1.0]), 1000.0, seed=1)
    with pytest.raises(ValueError):
        # n = sum(alphas) >= 1: explosive
        simulate_hawkes_multiexp(0.5, np.array([0.6, 0.5]), np.array([5.0, 0.2]), 1000.0, seed=1)
    with pytest.raises(ValueError):
        # empty alphas/betas
        simulate_hawkes_multiexp(0.5, np.array([]), np.array([]), 1000.0, seed=1)


def test_fit_multiexp_rejects_invalid_k_and_betas_init():
    times = np.array([1.0, 2.0, 3.0, 4.0])
    with pytest.raises(ValueError):
        fit_hawkes_multiexp(times, 10.0, K=0)
    with pytest.raises(ValueError):
        fit_hawkes_multiexp(times, 10.0, K=2, betas_init=np.array([1.0]))  # wrong length
    with pytest.raises(ValueError):
        fit_hawkes_multiexp(times, 10.0, K=1, betas_init=np.array([-1.0]))  # non-positive
    with pytest.raises(ValueError):
        fit_hawkes_multiexp(np.array([1.0]), 10.0, K=1)  # < 2 events


def _simulate_planted_2exp(seed: int) -> np.ndarray:
    return simulate_hawkes_multiexp(
        PLANTED_MU, PLANTED_ALPHAS, PLANTED_BETAS, PLANTED_T_END, seed=seed
    )


@pytest.fixture(scope="module")
def planted_sensitivity() -> dict[int, MultiExpFit]:
    """Fit K=1,2,3 ONCE on the planted 2-exp dataset and share across the
    headline K-sensitivity tests below (via `branching_ratio_sensitivity`,
    exercising that convenience wrapper directly) -- refitting K=1/2/3
    independently per test would multiply the (K=3 dominated) runtime by
    the number of tests that need it, which the runtime budget does not
    allow."""
    times = _simulate_planted_2exp(seed=42)
    return branching_ratio_sensitivity(times, PLANTED_T_END, Ks=(1, 2, 3))


def test_multiexp_k1_underestimates_planted_two_timescale_kernel(planted_sensitivity):
    """THE headline test: K=1 demonstrably underestimates n on genuinely
    2-timescale data (docs/research/02 §4 pitfall 3's claim, made concrete).

    True n=0.6 (alpha=(0.25,0.35), beta=(5,0.2), timescales 25x apart). A
    single exponential cannot represent both timescales at once and, per
    the literature, systematically underestimates the total kernel mass by
    over-weighting the fast component's fast decay -- assert n̂₁ is
    DEMONSTRABLY below 0.6, not just "not exactly 0.6": n̂₁ < 0.6 - 0.03.
    """
    fit_k1 = planted_sensitivity[1]

    assert fit_k1.n < PLANTED_N - 0.03, (
        f"expected K=1 to demonstrably underestimate n (< {PLANTED_N - 0.03}), "
        f"got n_hat={fit_k1.n}"
    )


def test_multiexp_k2_recovers_planted_two_timescale_kernel(planted_sensitivity):
    """K=2 (matching the true kernel's component count) recovers n within ±0.06."""
    fit_k2 = planted_sensitivity[2]

    assert fit_k2.converged
    assert abs(fit_k2.n - PLANTED_N) < 0.06, f"n_hat={fit_k2.n}, true n={PLANTED_N}"


def test_multiexp_k3_on_two_exp_data_does_not_blow_up(planted_sensitivity):
    """K=3 (over-parameterized relative to the true K=2 kernel) should still
    land in the right ballpark (±0.08) and converge, demonstrating the
    over-parameterization tolerance noted in fit_hawkes_multiexp's
    identifiability caveat -- the extra component should not run away to a
    degenerate/explosive solution."""
    fit_k3 = planted_sensitivity[3]

    assert fit_k3.converged
    assert abs(fit_k3.n - PLANTED_N) < 0.08, f"n_hat={fit_k3.n}, true n={PLANTED_N}"
    assert fit_k3.n < 1.0
    assert np.all(np.isfinite(fit_k3.alphas))
    assert np.all(np.isfinite(fit_k3.betas))


def test_multiexp_loglik_rejects_invalid_parameters():
    """Guard: mu<=0, any beta<=0, any alpha<0, or n=sum(alpha)>=1 -> -inf."""
    from microstructure.estimators.hawkes import hawkes_multiexp_loglik

    times = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
    t_end = 10.0
    good_alphas = np.array([0.2, 0.2])
    good_betas = np.array([5.0, 0.5])

    assert hawkes_multiexp_loglik(times, t_end, 0.0, good_alphas, good_betas) == -np.inf
    assert hawkes_multiexp_loglik(times, t_end, -0.1, good_alphas, good_betas) == -np.inf
    assert hawkes_multiexp_loglik(times, t_end, 0.3, good_alphas, np.array([5.0, -0.5])) == -np.inf
    assert hawkes_multiexp_loglik(times, t_end, 0.3, np.array([-0.1, 0.2]), good_betas) == -np.inf
    assert (
        hawkes_multiexp_loglik(times, t_end, 0.3, np.array([0.6, 0.5]), good_betas) == -np.inf
    )  # n=1.1 >= 1


def test_branching_ratio_sensitivity_returns_fit_per_k(planted_sensitivity):
    """branching_ratio_sensitivity is a thin convenience wrapper: one
    MultiExpFit per requested K, keyed by K. Reuses the module-scoped
    `planted_sensitivity` fixture (itself produced by this same function)
    rather than re-fitting, to stay inside the runtime budget."""
    results = planted_sensitivity

    assert set(results.keys()) == {1, 2, 3}
    assert isinstance(results[1], MultiExpFit)
    assert results[1].K == 1
    assert results[2].K == 2
    assert results[3].K == 3
    # Reproduce the K-sensitivity finding through the convenience wrapper too.
    assert results[1].n < results[2].n


def test_seasonal_baseline_confound_mimics_long_memory():
    """THE CONFOUND TRAP, sitting deliberately next to the headline
    long-memory test above: a K=1 -> K=2 rise in n̂ with a slow (small
    beta) second component is NOT unique evidence of long-memory
    self-excitation. It is ALSO produced by residual baseline
    non-stationarity that a constant-mu fit cannot represent, per the
    Filimonov & Sornette (2015) regime-switching trap already documented
    on `branching_count_variance` (see
    `test_regime_switching_produces_spurious_endogeneity`) -- this test
    shows the SAME confound also fools the multi-exponential MLE, not just
    the single-exponential MLE or the count-variance estimator.

    Ground truth here is a TRUE single-exponential Hawkes process (n=0.4,
    beta=2.0 -- no long memory whatsoever) with a piecewise-constant ±30%
    baseline wobble on 600s blocks (`np.tile([0.7, 1.3], 72)` over a
    60_000s window = 144 alternating 0.7x/1.3x-mean blocks of 600s/72... in
    `simulate_seasonal_hawkes_exp`'s bin convention this divides the 86400s
    day into 144 bins of 600s each, and t_end=60_000s covers a bit over half
    that period). Despite zero true long memory, K=1 -> K=2 shows
    n̂1=0.46 -> n̂2=0.83 (a jump exceeding 0.2) with a spurious near-zero
    beta component -- numerically indistinguishable in shape from the
    genuine-long-memory signature in
    `test_multiexp_k1_underestimates_planted_two_timescale_kernel` /
    `test_multiexp_k2_recovers_planted_two_timescale_kernel` above. THE
    POINT: n̂(K) sensitivity alone cannot distinguish "the true kernel has
    long memory" from "the baseline is not actually constant" -- per
    `fit_hawkes_multiexp`'s docstring, distinguishing them requires (a)
    checking the slow component's timescale 1/beta_slow against the
    deseasonalization bin width and fit-window length, and (b) the
    block-wise-constant-mu control.
    """
    shape = np.tile([0.7, 1.3], 72)
    t_end = 60_000.0
    times = simulate_seasonal_hawkes_exp(0.5, 0.4, 2.0, t_end, shape, seed=5)

    fit_k1 = fit_hawkes_multiexp(times, t_end, K=1)
    fit_k2 = fit_hawkes_multiexp(times, t_end, K=2)

    assert fit_k2.n - fit_k1.n > 0.2, (
        f"expected the baseline-drift confound to produce a spurious "
        f"n̂ jump > 0.2 (true n=0.4, no long memory at all); got "
        f"n̂1={fit_k1.n}, n̂2={fit_k2.n}"
    )
